"""

Revision ID: 28453487df9f
Revises: b96555433b49
Create Date: 2022-05-06 09:57:19.204574+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28453487df9f'
down_revision = 'b96555433b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('wakeup_time', sa.TIME(), nullable=True))
    op.create_index(op.f('ix_author_wakeup_time'), 'author', ['wakeup_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_wakeup_time'), table_name='author')
    op.drop_column('author', 'wakeup_time')
    # ### end Alembic commands ###