"""

Revision ID: 3166d041f025
Revises: b99cd73a41b2
Create Date: 2022-05-03 16:11:50.872079+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3166d041f025'
down_revision = 'b99cd73a41b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_profile', sa.Column('info', sa.JSON(), nullable=False))
    op.drop_column('author_profile', 'json_f')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_profile', sa.Column('json_f', mysql.JSON(), nullable=False))
    op.drop_column('author_profile', 'info')
    # ### end Alembic commands ###