"""empty message

Revision ID: 5c7f1f81426d
Revises: 509e1761ce5c
Create Date: 2022-07-12 11:11:23.695413+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c7f1f81426d'
down_revision = '509e1761ce5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies_authors_link')
    op.drop_table('friends_of_friends_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends_of_friends_link',
    sa.Column('author1_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author2_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author1_id'], ['author.id'], name='fk_friends_of_friends_link_author1_id_author'),
    sa.ForeignKeyConstraint(['author2_id'], ['author.id'], name='fk_friends_of_friends_link_author2_id_author'),
    sa.PrimaryKeyConstraint('author1_id', 'author2_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('movies_authors_link',
    sa.Column('movie_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name='fk_movies_authors_link_author_id_author'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='fk_movies_authors_link_movie_id_movie'),
    sa.PrimaryKeyConstraint('movie_id', 'author_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###