"""empty message

Revision ID: 6a3a72642aea
Revises: a9e0150222a5
Create Date: 2022-07-16 18:16:31.705173+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3a72642aea'
down_revision = 'a9e0150222a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###