"""

Revision ID: 6fa437335c80
Revises: eb0f96e08cd2
Create Date: 2022-04-27 20:17:31.994096+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fa437335c80'
down_revision = 'eb0f96e08cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_password', table_name='user')
    op.drop_index('ix_user_phonenumber', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phonenumber', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('roles', mysql.JSON(), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('date_joined', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_phonenumber', 'user', ['phonenumber'], unique=False)
    op.create_index('ix_user_password', 'user', ['password'], unique=False)
    # ### end Alembic commands ###