"""

Revision ID: 8ab8b0d7588b
Revises: 8ce8a37f5f21
Create Date: 2022-05-08 20:02:09.543976+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab8b0d7588b'
down_revision = '8ce8a37f5f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends_of_friends_link',
    sa.Column('author1_id', sa.Integer(), nullable=False),
    sa.Column('author2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author1_id'], ['author.id'], name=op.f('fk_friends_of_friends_link_author1_id_author')),
    sa.ForeignKeyConstraint(['author2_id'], ['author.id'], name=op.f('fk_friends_of_friends_link_author2_id_author')),
    sa.PrimaryKeyConstraint('author1_id', 'author2_id', name=op.f('pk_friends_of_friends_link'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends_of_friends_link')
    # ### end Alembic commands ###