"""

Revision ID: 8ce8a37f5f21
Revises: c5d145ab88fa
Create Date: 2022-05-08 16:26:54.179691+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ce8a37f5f21'
down_revision = 'c5d145ab88fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author_profile', 'info',
               existing_type=mysql.JSON(),
               nullable=True)
    op.add_column('category', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_category_parent_id_category'), 'category', 'category', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_category_parent_id_category'), 'category', type_='foreignkey')
    op.drop_column('category', 'parent_id')
    op.alter_column('author_profile', 'info',
               existing_type=mysql.JSON(),
               nullable=False)
    # ### end Alembic commands ###