"""empty message

Revision ID: a9e0150222a5
Revises: 5c7f1f81426d
Create Date: 2022-07-12 11:16:19.354599+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e0150222a5'
down_revision = '5c7f1f81426d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends_of_friends_link',
    sa.Column('author1_id', sa.Integer(), nullable=False),
    sa.Column('author2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author1_id'], ['author.id'], name=op.f('fk_friends_of_friends_link_author1_id_author')),
    sa.ForeignKeyConstraint(['author2_id'], ['author.id'], name=op.f('fk_friends_of_friends_link_author2_id_author')),
    sa.PrimaryKeyConstraint('author1_id', 'author2_id', name=op.f('pk_friends_of_friends_link'))
    )
    op.create_table('movies_authors_link',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name=op.f('fk_movies_authors_link_author_id_author')),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name=op.f('fk_movies_authors_link_movie_id_movie')),
    sa.PrimaryKeyConstraint('movie_id', 'author_id', name=op.f('pk_movies_authors_link'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies_authors_link')
    op.drop_table('friends_of_friends_link')
    # ### end Alembic commands ###