"""

Revision ID: b96555433b49
Revises: 3166d041f025
Create Date: 2022-05-03 22:49:02.820544+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96555433b49'
down_revision = '3166d041f025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_profile', sa.Column('protected', sa.BOOLEAN(), nullable=False))
    op.create_index(op.f('ix_author_profile_protected'), 'author_profile', ['protected'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_profile_protected'), table_name='author_profile')
    op.drop_column('author_profile', 'protected')
    # ### end Alembic commands ###