"""

Revision ID: b99cd73a41b2
Revises: e71e6e5e83ad
Create Date: 2022-05-03 15:00:34.829798+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99cd73a41b2'
down_revision = 'e71e6e5e83ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_profile', sa.Column('json_f', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_author_profile_json_f'), 'author_profile', ['json_f'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_profile_json_f'), table_name='author_profile')
    op.drop_column('author_profile', 'json_f')
    # ### end Alembic commands ###