"""

Revision ID: bd713e6a1009
Revises: 28453487df9f
Create Date: 2022-05-06 11:41:16.595222+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd713e6a1009'
down_revision = '28453487df9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('wakeup_day', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_author_wakeup_day'), 'author', ['wakeup_day'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_wakeup_day'), table_name='author')
    op.drop_column('author', 'wakeup_day')
    # ### end Alembic commands ###