"""

Revision ID: c5d145ab88fa
Revises: bd713e6a1009
Create Date: 2022-05-06 16:25:28.120833+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d145ab88fa'
down_revision = 'bd713e6a1009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_preview', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_preview', 'tags')
    # ### end Alembic commands ###