import app
"""

Revision ID: eb0f96e08cd2
Revises: 
Create Date: 2022-04-27 20:15:05.912204+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0f96e08cd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_profile',
    sa.Column('file', app.types.file_field.FileField(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_author_profile'))
    )
    op.create_table('category',
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image', app.types.file_field.FileField(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_table('manager',
    sa.Column('lastname', sa.TEXT(), nullable=False),
    sa.Column('firstname', sa.TEXT(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager'))
    )
    op.create_table('user',
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phonenumber', sa.VARCHAR(length=15), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_phonenumber'), 'user', ['phonenumber'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('author',
    sa.Column('lastname', sa.VARCHAR(length=255), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sex', sa.Enum('unknown', 'male', 'female', name='gender'), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.id'], name=op.f('fk_author_manager_id_manager')),
    sa.ForeignKeyConstraint(['profile_id'], ['author_profile.id'], name=op.f('fk_author_profile_id_author_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_author')),
    sa.UniqueConstraint('profile_id', name=op.f('uq_author_profile_id'))
    )
    op.create_index(op.f('ix_author_birthday'), 'author', ['birthday'], unique=False)
    op.create_index(op.f('ix_author_firstname'), 'author', ['firstname'], unique=False)
    op.create_index(op.f('ix_author_lastname'), 'author', ['lastname'], unique=False)
    op.create_index(op.f('ix_author_sex'), 'author', ['sex'], unique=False)
    op.create_table('movie',
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('watch_count', sa.INTEGER(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('release_date', sa.DATE(), nullable=True),
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_movie_category_id_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie'))
    )
    op.create_index(op.f('ix_movie_name'), 'movie', ['name'], unique=False)
    op.create_index(op.f('ix_movie_release_date'), 'movie', ['release_date'], unique=False)
    op.create_index(op.f('ix_movie_watch_count'), 'movie', ['watch_count'], unique=False)
    op.create_table('movie_preview',
    sa.Column('images', app.types.file_field.FileField(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name=op.f('fk_movie_preview_movie_id_movie')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie_preview')),
    sa.UniqueConstraint('movie_id', name=op.f('uq_movie_preview_movie_id'))
    )
    op.create_table('movies_authors_link',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name=op.f('fk_movies_authors_link_author_id_author')),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name=op.f('fk_movies_authors_link_movie_id_movie')),
    sa.PrimaryKeyConstraint('movie_id', 'author_id', name=op.f('pk_movies_authors_link'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies_authors_link')
    op.drop_table('movie_preview')
    op.drop_index(op.f('ix_movie_watch_count'), table_name='movie')
    op.drop_index(op.f('ix_movie_release_date'), table_name='movie')
    op.drop_index(op.f('ix_movie_name'), table_name='movie')
    op.drop_table('movie')
    op.drop_index(op.f('ix_author_sex'), table_name='author')
    op.drop_index(op.f('ix_author_lastname'), table_name='author')
    op.drop_index(op.f('ix_author_firstname'), table_name='author')
    op.drop_index(op.f('ix_author_birthday'), table_name='author')
    op.drop_table('author')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_phonenumber'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_table('user')
    op.drop_table('manager')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    op.drop_table('author_profile')
    # ### end Alembic commands ###